version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: laravel-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: distributor
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
        volumes:
            - dbdata:/var/lib/mysql

    web:
        image: nginx:latest
        container_name: laravel-web
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

volumes:
    dbdata:
